# Generated by Django 5.0.4 on 2024-04-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomersApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
