# Generated by Django 5.0.4 on 2024-04-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomersApp', '0003_customer_email_customer_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.TextField(max_length=20, unique=True),
        ),
    ]
